### ISSUE TITLE
KeyError: 'countryName'

### ISSUE THREAD

**Issue by nealmcb** [lachendeKatze/skill-iss-location#1]
When I install skill-iss-location on my Mark 1, and say "Mycroft, where's the space station", it says *An error occurred while processing a request in ISSLocationSkill*, and I get this in `/var/log/mycroft-skills.log`

```
2017-07-09 22:45:43,981 - mycroft.skills.core - ERROR - An error occurred while processing a request in ISSLocationSkill
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.17-py2.7.egg/mycroft/skills/core.py", line 251, in receive_handler
    handler(message)
  File "/opt/mycroft/skills/skill-iss-location/__init__.py", line 64, in handle_intent
    toponym = toponymObj['countryName']
KeyError: 'countryName'
```

**Comment by lachendeKatze** [comment]
have you registered for a geonames account, activated webservices for your geonames acct and inserted your user name into the url string for geonames?

**Comment by nealmcb** [comment]
Hmm?  I have no idea what that would involve, and didn't see any documentation about it.

**Comment by lachendeKatze** [comment]
Maybe this is the issue then, because I have been running the skill successfully since posting it.
if you go to www.geonames.org/login you can create a new account and the username you chose will go into the username part of the url. Additionally after activating your account, you have to activate web services, here is the info:
http://www.geonames.org/export/web-services.html

Maybe this process is unclear in my Hackster.io write-up?
